version: '3.8'

services:
  geobingo:
    build: .
    ports:
      - "8080:8080"
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
      - WEBSOCKET_PORT=8080
      - API_PORT=8000
    command: npm start
